// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"powerview/internal/app"
	"powerview/internal/client/gateway"
	"powerview/internal/client/gateway/gatewayhttpclient"
	"powerview/internal/server"
)

// Injectors from wire.go:

func CreateApp() (app.App, error) {
	client, err := gatewayhttpclient.NewGatewayHttpClient()
	if err != nil {
		return app.App{}, err
	}
	instance, err := gateway.NewInstance(client)
	if err != nil {
		return app.App{}, err
	}
	httpServer, err := server.NewServer()
	if err != nil {
		return app.App{}, err
	}
	appApp, err := app.NewApp(instance, httpServer)
	if err != nil {
		return app.App{}, err
	}
	return appApp, nil
}
